name: Build Docs

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Regenerate design tokens"]
    types:
      - complete

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npx sass  --no-source-map src/scss:public/css
          npx @11ty/eleventy --pathprefix=tokens

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}
